//! Discover pre-built helper binaries under `embedded/helper/<triple>/` and
//! emit a manifest module under `OUT_DIR/helper_manifest.rs` that the
//! `runtime::helper` module `include!`s.  Empty (no targets) is a valid
//! state — engine then routes via the constrained shell fallback.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=embedded/helper");
    println!("cargo:rerun-if-env-changed=ORDIUS_SKIP_HELPER_EMBED");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let manifest_path = out_dir.join("helper_manifest.rs");
    if env::var("ORDIUS_SKIP_HELPER_EMBED").is_ok() {
        fs::write(&manifest_path, empty_manifest()).unwrap();
        return;
    }
    let root = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap()).join("embedded/helper");
    if !root.exists() {
        fs::write(&manifest_path, empty_manifest()).unwrap();
        return;
    }
    let mut targets = Vec::new();
    for entry in fs::read_dir(&root).unwrap() {
        let entry = entry.unwrap();
        if !entry.file_type().unwrap().is_dir() {
            continue;
        }
        let triple = entry.file_name().to_string_lossy().into_owned();
        if triple == ".gitkeep" {
            continue;
        }
        let bin_path = entry.path().join(helper_filename(&triple));
        if !bin_path.exists() {
            continue;
        }
        let bytes = fs::read(&bin_path).unwrap();
        let sha = sha256_hex(&bytes);
        let abs = bin_path.canonicalize().unwrap();
        targets.push((triple, abs.to_string_lossy().into_owned(), sha, bytes.len()));
    }
    let mut src = String::from(
        "// auto-generated by build.rs; do not edit\n\n\
         /// Embedded helper manifest generated at build time.\n",
    );
    src.push_str("pub const HELPER_MANIFEST: HelperManifest = HelperManifest {\n");
    let version = env!("CARGO_PKG_VERSION");
    writeln!(&mut src, "    version: \"{version}\",").unwrap();
    src.push_str("    targets: &[\n");
    for (triple, path, sha, size) in &targets {
        src.push_str("        HelperTarget {\n");
        writeln!(&mut src, "            triple: \"{triple}\",").unwrap();
        writeln!(
            &mut src,
            "            bytes: include_bytes!(\"{}\"),",
            path.replace('\\', "/")
        )
        .unwrap();
        writeln!(&mut src, "            sha256: \"{sha}\",").unwrap();
        writeln!(&mut src, "            size: {size},").unwrap();
        src.push_str("        },\n");
    }
    src.push_str("    ],\n");
    src.push_str("};\n");
    fs::write(&manifest_path, src).unwrap();
}

fn empty_manifest() -> String {
    let version = env!("CARGO_PKG_VERSION");
    format!(
        "// auto-generated by build.rs; do not edit\n\n\
         /// Embedded helper manifest generated at build time.\n\
         pub const HELPER_MANIFEST: HelperManifest = HelperManifest {{\n\
         \x20\x20\x20\x20version: \"{version}\",\n\
         \x20\x20\x20\x20targets: &[],\n\
         }};\n"
    )
}

fn helper_filename(triple: &str) -> &'static str {
    if triple.contains("windows") {
        "ordius-helper.exe"
    } else {
        "ordius-helper"
    }
}

fn sha256_hex(bytes: &[u8]) -> String {
    use sha2::{Digest, Sha256};
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    let digest = hasher.finalize();
    let mut hex = String::with_capacity(digest.len() * 2);
    for byte in &digest {
        write!(&mut hex, "{:02x}", *byte).unwrap();
    }
    hex
}
